### ISSUE TITLE
Layout improvement

### ISSUE THREAD

**Issue by edysegura** [univas-first-exam/luizfelipe-paycheck#2]
This layout

![image](https://cloud.githubusercontent.com/assets/5324414/10762558/b0661b4e-7cad-11e5-8a19-e9ee34a3d221.png)

should be something like that

![image](https://cloud.githubusercontent.com/assets/5324414/10762571/c5b39396-7cad-11e5-8c95-a76764b9b1e6.png)

**Comment by edysegura** [comment]
Also your layout is pretty similar what Julio did in his exam.

**Comment by Liipe** [comment]
![image](https://cloud.githubusercontent.com/assets/10839872/10777859/dad6476a-7d06-11e5-904e-776c5c4aba82.png)

Layout revised.
