### ISSUE TITLE
Wrong calculation

### ISSUE THREAD

**Issue by edysegura** [univas-first-exam/luizfelipe-paycheck#3]
This application isn't doing the right calculation due to syntax error.

![image](https://cloud.githubusercontent.com/assets/5324414/10762697/3c92c93c-7cae-11e5-9e70-66eb1d003253.png)

**Comment by Liipe** [comment]
Está funcionando porém, como fiz igual à sua correção não consegui manter o mesmo html e css e também peguei o mesmo da sua correção. Obrigado

![Uploading image.png…]()

**Comment by Liipe** [comment]
Está funcionando porém, como fui tentando arrumar tudo da mesma maneira como você ia corrigindo a prova em sala tive que pegar o html e css da correção para manter compátivel. Obrigado.

![image](https://cloud.githubusercontent.com/assets/10839872/11170492/57a2441e-8bbd-11e5-8bb6-1395309d7dcb.png)

**Comment by edysegura** [comment]
Legal!! O importante é manter o contato com a tecnologia.
